/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandupRouteImport } from './routes/standup'
import { Route as IndexRouteImport } from './routes/index'

const StandupRoute = StandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/standup': typeof StandupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/standup': typeof StandupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/standup': typeof StandupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/standup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/standup'
  id: '__root__' | '/' | '/standup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StandupRoute: typeof StandupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standup': {
      id: '/standup'
      path: '/standup'
      fullPath: '/standup'
      preLoaderRoute: typeof StandupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StandupRoute: StandupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
