/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandupRouteImport } from './routes/standup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrsPrNumberRouteImport } from './routes/prs.$prNumber'

const StandupRoute = StandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsPrNumberRoute = PrsPrNumberRouteImport.update({
  id: '/prs/$prNumber',
  path: '/prs/$prNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standup': typeof StandupRoute
  '/prs/$prNumber': typeof PrsPrNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standup': typeof StandupRoute
  '/prs/$prNumber': typeof PrsPrNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standup': typeof StandupRoute
  '/prs/$prNumber': typeof PrsPrNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/standup' | '/prs/$prNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/standup' | '/prs/$prNumber'
  id: '__root__' | '/' | '/login' | '/standup' | '/prs/$prNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StandupRoute: typeof StandupRoute
  PrsPrNumberRoute: typeof PrsPrNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standup': {
      id: '/standup'
      path: '/standup'
      fullPath: '/standup'
      preLoaderRoute: typeof StandupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs/$prNumber': {
      id: '/prs/$prNumber'
      path: '/prs/$prNumber'
      fullPath: '/prs/$prNumber'
      preLoaderRoute: typeof PrsPrNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StandupRoute: StandupRoute,
  PrsPrNumberRoute: PrsPrNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
